[workspace]
members = [
    "crates/client",
    "crates/server",
    "crates/orchestrator",
    "crates/gatekeeper",
    "crates/broker",
    "crates/spatial_server",
    "shared/network-protocol",
    "shared/internal-communication-protocol",
    "shared/client-communication-protocol",
    "shared/web-communication-protocol", "shared/custom-id", "shared/mmo-math-tools"]
resolver = "2"

[workspace.dependencies]
tokio = "1.52.3"
bytes = "1.11.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
bitcode = "0.6.9"
ahash = "0.8.12"
rand = "0.10.1"
mathtools = "0.1.0"
bevy = { version = "0.18.1", default-features = false }


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

# Optimisation globale pour les builds en release (impacte tous les crates)
[profile.release]
opt-level = 3
lto = "thin"
