version: '3.8'

services:
  dbgate:
    image: dbgate/dbgate
    ports:
      - "8081:3000"
    networks:
      - game-network
    environment:
      CONNECTIONS: con1,con2
      # Postgres (utilise les variables du .env)
      LABEL_con1: Postgres
      ENGINE_con1: postgres@dbgate-plugin-postgres
      SERVER_con1: db
      USER_con1: ${POSTGRES_USER}
      PASSWORD_con1: ${POSTGRES_PASSWORD}
      PORT_con1: 5432
      DATABASE_con1: ${POSTGRES_DB}
      # Redis
      LABEL_con2: Redis
      ENGINE_con2: redis@dbgate-plugin-redis
      SERVER_con2: redis
      PORT_con2: 6379

  db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../crates/gatekeeper/migrations:/migrations:ro
    networks:
      - game-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  server-builder:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    image: uqac_t3_mmo-server:local
    command: ["echo", "✅ Build de l'image du serveur terminé avec succès !"]

  orchestrator:
    build:
      context: ..
      dockerfile: docker/orchestrator.Dockerfile
    ports:
      - "4000:4000"
    environment:
      - RUST_LOG=${RUST_LOG}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      redis:
        condition: service_started
      server-builder:
        condition: service_completed_successfully
    networks:
      - game-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/app

  gatekeeper:
    build:
      context: ..
      dockerfile: docker/gatekeeper.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RUST_LOG=${RUST_LOG}
      - ROCKET_ADDRESS=${ROCKET_ADDRESS}
      - ROCKET_PORT=${ROCKET_PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - game-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - game-network

networks:
  game-network:
    driver: bridge
    name: game-network

volumes:
  postgres_data: