version: '3.8'

services:
  bot_client:
    build:
      context: ..
      dockerfile: docker/client.Dockerfile
    # Empêche le conteneur de se fermer inopinément si la console se détache
    tty: true
    # Facultatif : limiter les ressources pour éviter qu'un bug ne crash ta machine
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 128M

networks:
  default:
    name: game-network
    external: true