[package]
name = "server"
version = "0.1.0"
edition = "2024"

[features] # cargo run -p server --features "dev"
dev = ["bevy/dynamic_linking"]

[dependencies]
client-communication-protocol = { path = "../../shared/client-communication-protocol" }
internal-communication-protocol = { path = "../../shared/internal-communication-protocol" }
network-protocol = { path = "../../shared/network-protocol" }
custom-id = { path = "../../shared/custom-id" }
aoi-model = { path = "../../shared/aoi-model" }

bytes = { workspace = true }
serde = { workspace = true }
bitcode = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
mathtools = { workspace = true }
bevy = { workspace = true, features = ["bevy_log", "debug", "bevy_state"] }
ahash = { workspace = true }

avian2d = "0.6.1"
