[package]
name = "spatial_server"
version = "0.1.0"
edition = "2024"

[dependencies]

internal-communication-protocol = { path = "../../shared/internal-communication-protocol" }
network-protocol = { path = "../../shared/network-protocol" }
custom-id = { path = "../../shared/custom-id" }

mathtools = { workspace = true }
bytes = { workspace = true }
ahash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

tiny_http = "0.12.0"